server:
  port: 8000

#默认使用spring-boot自带的Hikari（光）数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: yangyinfeng
    driver-class-name: com.mysql.jdbc.Driver
#Mybatis
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

# pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql